Optimize the CI pipeline.
* Validate git tags as SemVer strings.
* Publish on GitHub Release events instead of git tag events.
* Update the latest build on pushes to the develop branch.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -3,49 +3,35 @@ name: Build and Publish Docker Image
 on:
   push:
     branches:
-        - "main"
-        - "develop"
-    tags:
-      - "v*.*.*"
+      - develop
+  release:
+    types: [published]
 
 jobs:
-  docker:
+  publish:
     runs-on: ubuntu-latest
+    name: Publish Docker image to container registry
     steps:
-      -
-        name: Checkout
+      - name: Check out the repo
         uses: actions/checkout@v3
-      -
-        name: Set Docker Image and Tags
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ghcr.io/mitre-attack/attack-workbench-taxii-server
-          tags: |
-            # set latest tag for master branch
-            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
-            # set develop tag for develop branch
-            type=ref,event=branch,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
-            # set semver tag (vX.Y.Z) on git tag event
-            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
-            # set git short commit as Docker tag (e.g., sha-ad132f5)
-            type=sha
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      -
-        name: Login to GHCR
-        if: github.event_name != 'pull_request'
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Build and push
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta.outputs.tags }}
+
+      - name: Extract tag name
+        if: github.event_name == 'release'
+        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+
+      - name: Validate tag
+        if: github.event_name == 'release'
+        run: |
+          if ! [[ "${{ env.TAG }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
+            echo "Invalid tag format. The tag must follow the semantic versioning format: X.Y.Z or X.Y.Z-prerelease"
+            exit 1
+          fi
+
+      - name: Build and publish Docker image
+        run: |
+          echo $GITHUB_TOKEN | docker login ghcr.io -u mitre-attack --password-stdin
+          docker build . --tag ghcr.io/mitre-attack/attack-workbench-taxii-server:${TAG:-latest}
+          docker push ghcr.io/mitre-attack/attack-workbench-taxii-server:${TAG:-latest}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ env.TAG }}
